/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIMS_H_RPCGEN
#define _TIMS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define EPOCH_LEN 8
#define MIN_BLK_SZE 512
#define MSG_LEN 256
#define NAME_LEN 32
#define STRUCT_LEN 328

typedef char *name;

struct message {
	char to[NAME_LEN];
	char from[NAME_LEN];
	int datetime;
	char body[MSG_LEN];
};
typedef struct message message;

#define TIMS_PROG 24670117
#define TIMS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TIMS_PUT 1
extern  int * tims_put_1(message *, CLIENT *);
extern  int * tims_put_1_svc(message *, struct svc_req *);
#define TIMS_GET 2
extern  message * tims_get_1(name *, CLIENT *);
extern  message * tims_get_1_svc(name *, struct svc_req *);
extern int tims_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TIMS_PUT 1
extern  int * tims_put_1();
extern  int * tims_put_1_svc();
#define TIMS_GET 2
extern  message * tims_get_1();
extern  message * tims_get_1_svc();
extern int tims_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_name (XDR *, name*);
extern  bool_t xdr_message (XDR *, message*);

#else /* K&R C */
extern bool_t xdr_name ();
extern bool_t xdr_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIMS_H_RPCGEN */
