/*  Scott Felch
	W00750298
	felchs@students.wwu.edu
	3 February 2013
	HW 3.56
	
	Consider the following assembly code:
		
		x at %ebp+8, n at %ebp+12
	movl	8(%ebp), 	%esi
	movl	12(%ebp), 	%ebx	
	movl	$-1,		%edi
	movl	$1,			%edx
.L2
	movl	%edx,		%eax
	andl	%esi,		%eax
	xorl	%eax,		%edi
	movl	%ebx,		%ecx
	sall	%cl,		%edx
	testl	%edx,		%edx
	jne		.L2
	movl	%edi,		%eax

	The preceding code was generated by compiling C code that had the following
	overall form:
	
	int loop(int x, int n)
	{
		int result = ______;
		int mask;
		for (mask = ______; mask ______; mask = ______) {
			result ^= ________;
		}

		return result;
	}
	
	Your task is to fill in the missing parts of the C code to get a program
	equivalent to the gneerated assembly code. Recall that the result of the
	function is return in register %eax. You will find it helpful to examine
	the assembly code before, during, and after the loop to form a consistent
	mapping between the registers and the program variables.
	
	A. Which registers hold program values x, n, and mask?
	B. What are the initial values of result and mask?
	C. What is the test condition for mask?
	D. How does mask get updated?
	E. HOw does result get updated?
	F. Fill in all the missing parts of the C code.
	
	*/
	
int loop(int x, int n) {
	int result = x;
	int mask;
	for (mask = ______; mask ______; mask = ______) {
		result ^= ________;
	}

	return result;
}
